spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb?createDatabaseIfNotExist=true
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
      jdbc:
        time_zone: UTC


