server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/impubudu/JavaTraining
          search-paths:
            - 'service-config/*service'
          #username: root
          #passphrase: 12345
