spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/emsEmployeeDB?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx@
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
security:
  oauth2:
    resource:
      token-info-uri: http://oauth2-service:8282/oauth/check_token
    client:
      client-id: web
      client-secret: webpass
