spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/batchdb?createDatabaseIfNotExist=true
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    initialization-mode: always


  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

  batch:
    job:
      enabled: false
    initialize-schema: ALWAYS



